Assignment2/Models/ListInterventionViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Assignment2.Models
{
    public class ListInterventionViewModel
    
    {
           
            [Display(Name = "Client District")]
            public string ClientDistrict { get; set; }
            [Display(Name = "Client Name")]
            public string ClientName { get; set; }
            [Display(Name = "Intervention Type Name")]
            public string InterventionTypeName { get; set; }
            [Display(Name = "Intervention Cost")]
            public decimal InterventionCost { get; set; }
            [Display(Name = "Intervention Hours")]
            public decimal InterventionHours { get; set; }
            [Display(Name = "Create Date")]
            public DateTime CreateDate { get; set; }
            public int Status { get; set; }
            [Display(Name = "Intervention Id")]
            public int InterventionId { get; set; }

        }
    }

Assignment2/Controllers/SiteEngineerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Assignment2.Data_Access_Layer;
using Assignment2.Models;
using Assignment2.Helpers;
using System.Web.UI.WebControls;
using WebApplication2.Exceptions;

namespace Assignment2.Controllers
{
    /// <summary>
    /// With the help of SiteEngineer View And InterventionViewModel, ClientViewModel this controller is used for create edit view Interventions, clients
    /// </summary>
    [Authorize(Roles = Roles.SITE_ENGINEER)]
    public class SiteEngineerController : Controller
    {
        private SiteEngineerHelper siteEngineerHelper = new SiteEngineerHelper();

        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Index(string Button)
        {
            return RedirectToAction(Button);
        }

        /// <summary>
        /// This method is used to list all intervention
        /// </summary>
        /// <returns>view</returns>
        public ActionResult ListInterventions()
        {
            IList<ListInterventionViewModel> viewModel = new List<ListInterventionViewModel>();
            try
            {
                viewModel = siteEngineerHelper.ListInterventions();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }

        /// <summary>
        /// This method is used for the view page of creating interventions
        /// </summary>
        /// <returns>View</returns>
        public ActionResult CreateIntervention()
        {
            var viewModel = new CreateNewInterventionViewModel();
            try
            {
                var clients = siteEngineerHelper.ListCurrentClients();
                if (clients.Count == 0)
                {
                    Exception ex = new NoClientCreatedException();
                    ModelState.AddModelError("alert", ex.Message);
                }
                var listItems = new List<ListItem>();
                foreach (var client in clients)
                {
                    listItems.Add(new ListItem { Text = client.ClientName, Value = client.ClientId.ToString() });
                }
                ViewBag.clients = new SelectList(listItems, "Value", "Text");
                var interventionTypes = siteEngineerHelper.ListInterventionTypes();
                var listItems2 = new List<ListItem>();
                foreach (var type in interventionTypes)
                {
                    listItems2.Add(new ListItem { Text = type.InterventionTypeName, Value = type.InterventionTypeId.ToString() });
                }
                ViewBag.interventionTypes = new SelectList(listItems2, "Value", "Text", interventionTypes.FirstOrDefault());
                viewModel.interventionCost = interventionTypes.FirstOrDefault().InterventionTypeCost;
                viewModel.interventionHours = interventionTypes.FirstOrDefault().InterventionTypeHours;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }

        /// <summary>
        /// This method is used for calling CreateIntervention method to create a new intervention by passing user enterd values in fields
        /// </summary>
        /// <returns>View</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateIntervention(CreateNewInterventionViewModel viewModel)
        {
            try
            {
                siteEngineerHelper.CreateIntervention(viewModel.clientId, viewModel.interventionTypeId, viewModel.interventionCost, viewModel.interventionHours);
                ModelState.AddModelError("success", "Intervention Created Successfully!");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            var clients = siteEngineerHelper.ListCurrentClients();
            var listItems3 = new List<ListItem>();
            foreach (var client in clients)
            {
                listItems3.Add(new ListItem { Text = client.ClientName, Value = client.ClientId.ToString() });
            }
            ViewBag.clients = new SelectList(listItems3, "Value", "Text", listItems3.Where(i => i.Value.Equals(viewModel.clientId)).Select(i => i));
            var interventionTypes2 = siteEngineerHelper.ListInterventionTypes();
            var listItems4 = new List<ListItem>();
            foreach (var type in interventionTypes2)
            {
                listItems4.Add(new ListItem { Text = type.InterventionTypeName, Value = type.InterventionTypeId.ToString() });
            }
            ViewBag.interventionTypes = new SelectList(listItems4, "Value", "Text", listItems4.Where(i => i.Value.Equals(viewModel.interventionTypeId)).Select(i => i));
            return View(viewModel);
        }


        /// <summary>
        /// This method is used for view page of Edit Interventions
        /// </summary>
        /// <param name="id">Id of intervention to be edited</param>
        /// <returns>View</returns>
        public ActionResult EditIntervention(int? id)
        {
            var intId = (id == null) ? 0 : (int)id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var intervention = new SiteEngineerHelper();
            var inter = intervention.GetIntervention(intId);
            if (inter == null)
            {
                return HttpNotFound();
            }
            var statuslist = intervention.GetPossibleStatusUpdateForInterventionForSiteEngineer(inter.Status);
            ViewBag.Status = new SelectList(statuslist.Keys);
            return View(inter);
        }


        /// <summary>
        /// This method is used for calling UpdateIntervention method to update an intervention by passing user enterd values in fields
        /// </summary>
        /// <returns>View</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditIntervention(ListInterventionViewModel InterList)
        {
            var viewModel = new ListInterventionViewModel();
            if (ModelState.IsValid)
            {
                InterList.comments = (Utils.getInstance.isNullOrEmpty(InterList.comments)) ? string.Empty : InterList.comments;
                var condition = (Utils.getInstance.isNullOrEmpty(InterList.Condition)) ? 0 : (int)InterList.Condition;
                if (!Utils.getInstance.isNullOrEmpty(InterList.Status))
                {
                    var inter = siteEngineerHelper.UpdateIntervention(InterList.InterventionId, InterList.comments, condition, InterList.InterventionCost, InterList.InterventionHours, InterList.Status);
                    ModelState.AddModelError("success", "Intervention Updated Successfully!");
                }
                else
                {
                    ModelState.AddModelError("alert", "Cannot edit already Cancelled intervention");

                }
                var statuslist = siteEngineerHelper.GetPossibleStatusUpdateForInterventionForSiteEngineer(InterList.Status);
                ViewBag.Status = new SelectList(statuslist.Keys);
            }
            return View(InterList);
        }

        /// <summary>
        /// This method is used to view all assosiated Clients to user
        /// </summary>
        /// <returns>View</returns>
        public ActionResult ViewClients()
        {
            IList<ListClientsViewModel> viewModel = new List<ListClientsViewModel>();
            try
            {
                viewModel = siteEngineerHelper.ListOfClients();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }




        /// <summary>
        /// This method is used for list all clients in the same district
        /// </summary>
        /// <returns>View</returns>
        public ActionResult ViewClientsInDistrict()
        {
            IList<ListClientsViewModel> viewModel = new List<ListClientsViewModel>();
            try
            {
                viewModel = siteEngineerHelper.ListOfClientsInDistrict();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }

        /// <summary>
        /// This method is used to list all Interventions assosiated to client
        /// </summary>
        /// <param name="id">Client ID</param>
        /// <returns>View</returns>
        public ActionResult ViewClientsInterventions(int? id)
        {
            int clientId = (id == null) ? 0 : (int)id;
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IList<ListInterventionViewModel> viewModel = new List<ListInterventionViewModel>();
            try
            {
                viewModel = siteEngineerHelper.ListOfClientsInterventions(clientId);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }

        /// <summary>
        /// This method is used for the view page of creating clients
        /// </summary>
        /// <returns>View</returns>
        public ActionResult CreateClient()
        {
            var viewModel = new CreateNewClientViewModel();
            viewModel.clientDistrict = siteEngineerHelper.GetDistrictForUser();
            return View(viewModel);
        }

        /// <summary>

Assignment2/Views/SiteEngineer/CreateClient.cshtml
@using Assignment2.Models
@model CreateNewClientViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create New Client</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationMessage("success", new { @class = "text-success" })

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.clientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.clientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.clientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clientLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.clientLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.clientLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clientDistrict, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.clientDistrict, new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.clientDistrict, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("View All Clients", "ViewClients")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment2/Views/SiteEngineer/CreateIntervention.cshtml
@using Assignment2.Models
@model CreateNewInterventionViewModel


@{
        ViewBag.Title = "Enter Details";
}

<h2>Create New Intervention</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
    
        @Html.ValidationMessage("success", new { @class = "text-success" })
        @Html.ValidationMessage("alert", new { @class = "text-danger" })

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (ViewData.ContainsKey("clients"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.clientName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.clientId , (SelectList)ViewBag.clients , "Select a Client", htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.clientName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.clientId, (SelectList)ViewBag.clients, "Select a Client", htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
        }


        <div class="form-group">
            @Html.LabelFor(model => model.interventionTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.interventionTypeId, (SelectList)ViewBag.interventionTypes, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.interventionCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.interventionCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.interventionCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.interventionHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.interventionHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.interventionHours, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (ViewData.ContainsKey("alert"))
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" readonly disabled/>
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
}
<div>
    @Html.ActionLink("View All Interventions", "ListInterventions")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

 

Assignment2/Views/SiteEngineer/EditIntervention.cshtml
@using Assignment2.Models;
@model Assignment2.Models.ListInterventionViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Intervention</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationMessage("success", new { @class = "text-success" })
        @Html.ValidationMessage("alert", new { @class = "text-danger" })

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InterventionId)
        @Html.HiddenFor(model => model.InterventionCost)
        @Html.HiddenFor(model => model.InterventionHours)

        <div class="form-group">
            @Html.LabelFor(model => model.ClientName, "Client Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterventionTypeName, "Intervention Type Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterventionTypeName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>



        @if (Status.PROPOSED.Equals(Model.Status))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Condition, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Condition, "Condition", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>

        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Condition, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Condition, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Condition,"", new { @class = "text-danger" })
                
                </div>
            </div>

        }

        <div class="form-group">
            @Html.LabelFor(model => model.comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comments, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifyDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifyDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<hr />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment2/Views/SiteEngineer/Index.cshtml
@{
    ViewBag.Title = "Site Engineer Home Page";
}
<p>
    <br />
    <h2>@ViewBag.Title</h2>
</p>
@using (Html.BeginForm("Index", "SiteEngineer", FormMethod.Post, new { id = "submitForm" }))
{
    <hr />
    <p>
        <button id="ButtonCreateNewClient" name="Button" style="width:400px" value="CreateClient">Create New Client</button>
    </p>
    <p>
        <button id="ButtonViewClient" name="Button" style="width:400px" value="ViewClients">View All Clients Created By You</button>
    </p>
    <p>
        <button id="ButtonViewAllClientsInSameDistrict" name="Button" style="width:400px" value="ViewClientsInDistrict">View All Clients In Same District</button>
    </p>
    <hr />
    <p>
        <button id="ButtonCreateIntervention" name="Button" style="width:400px" value="CreateIntervention">Create New Intervention</button>
    </p>
    <p>
        <button ID="ButtonViewInterventions" name="Button" style="width:400px" value="ListInterventions">View All Interventions Created By You</button>
    </p>
}

Assignment2/Views/SiteEngineer/ListInterventions.cshtml
@using Assignment2.Models
@model IEnumerable<ListInterventionViewModel>

@{
    ViewBag.Title = "All Interventions Created By You";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "CreateIntervention")
</p>
@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InterventionTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.InterventionTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterventionCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterventionHours)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditIntervention", new { id = item.InterventionId })
                </td>
            </tr>
        }
    </table>
}
else
{
    <hr />
    <div> <h3>No interventions created yet</h3> </div>
}

Assignment2/Views/SiteEngineer/ViewClients.cshtml
@using Assignment2.Models
@model IEnumerable<ListClientsViewModel>

@{
    ViewBag.Title = "Your Clients";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "CreateClient")
</p>
@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.clientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.clientLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.createDate)
            </th>
            <th>
                @Html.DisplayName("Interventions")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.clientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.clientLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.createDate)
                </td>
                <td>
                    @Html.ActionLink("View Associated Interventions", "ViewClientsInterventions", new { id = item.clientID })
                </td>
            </tr>
        }

    </table>
}
else
{
    <hr />
    <div> <h3>You have no Clients</h3> </div>
}

Assignment2/Views/SiteEngineer/ViewClientsInDistrict.cshtml
@using Assignment2.Models
@model IEnumerable<ListClientsViewModel>

@{
    ViewBag.Title = "Clients In Your District";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "CreateClient")
</p>
@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.clientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.clientLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.createDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.createdBy)
            </th>
            <th>
                @Html.DisplayName("Interventions")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.clientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.clientLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.createDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.createdBy)
                </td>
                <td>
                    @Html.ActionLink("View Associated Interventions", "ViewClientsInterventions", new { id = item.clientID })
                </td>
            </tr>
        }

    </table>
}
else
{
    <hr />
    <div> <h3>You have no Clients</h3> </div>
}

Assignment2/Views/SiteEngineer/ViewClientsInterventions.cshtml
@using Assignment2.Models
@model IEnumerable<ListInterventionViewModel>

@{
    ViewBag.Title = "Intervention Details";
}

<h2>Intervention Details</h2>


<p>
    @Html.ActionLink("Create New", "CreateIntervention")
</p>

@if (Model.Any())
{
    <table class="table">
        <tr>


            <th>
                @Html.DisplayNameFor(model => model.InterventionTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.InterventionTypeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterventionCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterventionHours)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditIntervention", new { id = item.InterventionId })
                </td>
            </tr>
        }

    </table>
}
else
{
    <hr />
    <div> <h3>Sorry, No interventions to display</h3> </div>
}